apiVersion: v1
kind: Service
metadata:
  name: rubyapp-service
  labels:
    app: rubyapp-service
spec:
  ports:
  - port: 3333
    name: http
    targetPort: 3333
  selector:
    app: helloworld-rubyapp